### ISSUE TITLE
panic: runtime listed a std package we can't find: arena

### ISSUE THREAD

**Issue by cpu0x00** [Tylous/Freeze#4]
im getting this weird error everytime i try to run freeze no matter what mode exe/dll encrypted/notencrypted im have 0 experience with go and thats i cannot debug it myself :sweat_smile:  

```
exit status 1: # runtime
panic: runtime listed a std package we can't find: arena

goroutine 1 [running]:
main.listPackage({0xc00001c9dd, 0x5})
	/root/go/pkg/mod/mvdan.cc/garble@v0.7.2/shared.go:389 +0x734
main.(*transformer).handleDirectives(0x7fffa6f82948?, {0xc000047c00, 0x69, 0x2647?})
	/root/go/pkg/mod/mvdan.cc/garble@v0.7.2/main.go:952 +0x2e5
main.transformCompile({0xc000014ad0?, 0x171b?, 0xa3?})
	/root/go/pkg/mod/mvdan.cc/garble@v0.7.2/main.go:839 +0x75b
main.mainErr({0xc000014ab0, 0x9d, 0xa5})
	/root/go/pkg/mod/mvdan.cc/garble@v0.7.2/main.go:424 +0x855
main.main1()
	/root/go/pkg/mod/mvdan.cc/garble@v0.7.2/main.go:228 +0x177
main.main()
	/root/go/pkg/mod/mvdan.cc/garble@v0.7.2/main.go:135 +0x13
exit status 1

```

**Comment by cpu0x00** [comment]
fixed by changing line 42 is Utils/Utils.go to:

`cmd = exec.Command(bin, "GOBIN="+cwd+"/.lib/", "go", "install", "mvdan.cc/garble@latest")`

and rebuilding Freeze with the changes
